cicero/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls.defaults import patterns, url, include

from cicero import views, feeds


urlpatterns = patterns('',
    url(r'^$',                                   views.index, name='cicero_index'),

    url(r'^users/',                              include('scipio.urls')),
    url(r'^users/(\d+)/$',                       views.user, name='profile'),
    url(r'^users/(\d+)/topics/$',                views.user_topics),
    url(r'^users/self/$',                        views.edit_profile, name='cicero-self'),
    url(r'^users/self/openid/$',                 views.change_openid),
    url(r'^users/self/(personal|settings)/$',    views.post_profile),
    url(r'^users/self/deleted_articles/$',       views.deleted_articles,
                                                 {'user_only': True},
                                                 name='deleted_articles'),

    url(r'^mark_read/$',                         views.mark_read, name='cicero-mark-read'),
    url(r'^([a-z0-9-]+)/mark_read/$',            views.mark_read, name='cicero-mark-read-forum'),
    url(r'^deleted_articles/$',                  views.deleted_articles,
                                                 {'user_only': False},
                                                 name='all_deleted_articles'),

    url(r'^article_preview/$',                   views.article_preview, name='cicero-article-preview'),
    url(r'^article_edit/(\d+)/$',                views.article_edit, name='cicero-article-edit'),
    url(r'^article_vote/(\d+)/$',                views.article_vote),
    url(r'^article_delete/(\d+)/$',              views.article_delete),
    url(r'^article_undelete/(\d+)/$',            views.article_undelete),
    url(r'^article_publish/(\d+)/$',             views.article_publish),
    url(r'^article_spam/(\d+)/$',                views.article_spam),

    url(r'^spam_queue/$',                        views.spam_queue),
    url(r'^delete_spam/$',                       views.delete_spam),

    url(r'^topic_edit/(\d+)/$',                  views.topic_edit, name='cicero-topic-edit'),
    url(r'^topic_spawn/(\d+)/$',                 views.topic_spawn, name='cicero-topic-spawn'),

    url(r'^feeds/articles/([a-z0-9-]+)/$',       feeds.Article(), name='cicero_forum_feed'),
    url(r'^feeds/articles/([a-z0-9-]+)/(\d+)/$', feeds.Article(), name='cicero_topic_feed'),

    url(r'^([a-z0-9-]+)/$',                      views.forum, name='cicero-forum'),
    url(r'^([a-z0-9-]+)/(\d+)/$',                views.topic, name='cicero-topic'),
    url(r'^([a-z0-9-]+)/search/$',               views.search),
)

cicero/models.py
# -*- coding:utf-8 -*-
import os
from datetime import datetime, date, timedelta
from StringIO import StringIO

from django.db import models
from django.db import connection
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.core.files.base import ContentFile
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.utils.html import linebreaks, escape
from django.conf import settings
import scipio.signals
from scipio.models import Profile as ScipioProfile
import pingdjack

from cicero import fields
from cicero.filters import filters
from cicero.mutants import mutant
from cicero import utils
from cicero.utils import ranges, usertext

class Profile(models.Model):
    user = fields.AutoOneToOneField(User, related_name='cicero_profile', primary_key=True)
    filter = models.CharField(u'Фильтр', max_length=50, default='markdown',
                              choices=[(k, k) for k in filters.keys()])
    mutant = models.ImageField(upload_to='mutants', null=True, blank=True)
    read_articles = fields.RangesField(editable=False)
    moderator = models.BooleanField(default=False)

    def __unicode__(self):
        try:
            return unicode(self.user.scipio_profile)
        except ScipioProfile.DoesNotExist:
            pass
        return unicode(self.user)

    def save(self, **kwargs):
        if not self.mutant:
            self.generate_mutant()
        super(Profile, self).save(**kwargs)

    def get_absolute_url(self):
        return reverse('profile', args=[self.user_id])

    def generate_mutant(self):
        '''
        Создает, если возможно, картинку мутанта из OpenID.
        '''
        if self.mutant and os.path.exists(self.mutant.path):
            os.remove(self.mutant.path)
        if not settings.CICERO_OPENID_MUTANT_PARTS:
            return
        try:
            content = StringIO()
            mutant(self.user.scipio_profile.openid).save(content, 'PNG')
            self.mutant.save('%s.png' % self._get_pk_val(), ContentFile(content.getvalue()))
        except ScipioProfile.DoesNotExist:
            pass

    scipio.signals.created.connect(lambda sender, profile, **kwargs: profile.user.cicero_profile.generate_mutant())

    def unread_topics(self):
        '''
        Непрочитанные топики пользователя во всех форумах
        '''
        query = Q()
        for range in self.read_articles:
            query = query | Q(article__id__range=range)
        return Topic.objects.exclude(query).distinct()

    def set_news(self, objects):
        '''
        Проставляет признаки наличия новых статей переданным топикам или форумам
        '''
        if len(objects) == 0:
            return
        ids = [str(o.id) for o in objects]
        tables = 'cicero_article a, cicero_topic t'
        condition = 'topic_id = t.id' \
                    ' and a.deleted is null and a.spam_status = \'clean\'' \
                    ' and t.deleted is null and t.spam_status = \'clean\'' \
                    ' and t.created >= %s'
        if isinstance(objects[0], Forum):
            field_name = 'forum_id'
            condition += ' and forum_id in (%s)' % ','.join(ids)
        else:
            field_name = 'topic_id'
            condition += ' and topic_id in (%s)' % ','.join(ids)
        ranges = ' or '.join(['a.id between %s and %s' % range for range in self.read_articles])
        condition += ' and not (%s)' % ranges
        query = 'select %s, count(1) as c from %s where %s group by 1' % (field_name, tables, condition)
        old_topic_age = datetime.now().date() - timedelta(settings.CICERO_OLD_TOPIC_AGE)
        cursor = connection.cursor()
        cursor.execute(query,  [old_topic_age])
        counts = dict(cursor.fetchall())
        for obj in objects:
            obj.new = counts.get(obj.id, 0)

    def add_read_articles(self, articles):
        '''
        Добавляет новые статьи к списку прочитанных.

        Статьи передаются в виде queryset.
        '''

        # Нужно еще раз считать read_articles с "for update", чтобы параллельные транзакции
        # не затирали друг друга
        self.read_articles = (Profile.objects.select_for_update()
                                             .filter(pk=self._get_pk_val())
                                             .values_list('read_articles', flat=True)[0])

        query = Q()

        for range in self.read_articles:
            query = query | Q(id__range=range)

        ids = [a['id'] for a in articles.exclude(query).values('id')]
        merged = self.read_articles

        for range in ranges.compile_ranges(ids):
            merged = ranges.merge_range(range, merged)

        try:
            article = Article.objects.filter(created__lt=date.today() - timedelta(settings.CICERO_UNREAD_TRACKING_PERIOD)).order_by('-created')[0]
            merged = ranges.merge_range((0, article.id), merged)
        except IndexError:
            pass

        if self.read_articles != merged:
            self.read_articles = merged
            return True
        else:
            return False

    def set_votes(self, articles):
        '''
        Проставляет статьям признаки голосования за них от лица профиля.
        '''
        votes = self.vote_set.filter(article__in=[a.pk for a in articles])
        article_votes = dict((v.article_id, v) for v in votes)
        for article in articles:
            vote = article_votes.get(article.pk)
            article.vote_value = vote and vote.value
            article.voted_up = article.vote_value == 'up'
            article.voted_down = article.vote_value == 'down'

    def can_change_article(self, article):
        return self.moderator or (not article.from_guest() and article.author_id == self.user_id)

    def can_change_topic(self, topic):
        return self.can_change_article(topic.article_set.all()[0])

    def topics(self):
        return Topic.objects.filter(article__author=self).distinct().select_related('forum')


class Forum(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=255)
    group = models.CharField(max_length=255, blank=True)
    ordering = models.IntegerField(default=0)

    class Meta:
        ordering = ['ordering', 'group']

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return 'cicero.views.forum', [self.slug]

class TopicManager(models.Manager):
    def get_query_set(self):
        return super(TopicManager, self).get_query_set().filter(deleted__isnull=True)

class DeletedTopicManager(models.Manager):
    def get_query_set(self):
        return super(DeletedTopicManager, self).get_query_set().filter(deleted__isnull=False).order_by('-deleted')

class Topic(models.Model):
    forum = models.ForeignKey(Forum)
    subject = models.CharField(u'Тема', max_length=255)
    created = models.DateTimeField(default=datetime.now, db_index=True)
    deleted = models.DateTimeField(null=True, db_index=True, blank=True)
    spam_status = models.CharField(max_length=20, default='clean')

    objects = TopicManager()
    deleted_objects = DeletedTopicManager()

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        return self.subject

    def delete(self):
        Article.deleted_objects.filter(topic=self).delete()
        super(Topic, self).delete()

    @models.permalink
    def get_absolute_url(self):
        return 'cicero.views.topic', [self.forum.slug, self.id]

    def old(self):
        return self.created.date() < datetime.now().date() - timedelta(settings.CICERO_OLD_TOPIC_AGE)

    def spawned_from(self):
        if not hasattr(self, '_spawned_from'):
            try:
                self._spawned_from = self.spawned_from_article
            except Article.DoesNotExist:
                self._spawned_from = None
        return self._spawned_from

class ArticleManager(models.Manager):
    def get_query_set(self):
        return super(ArticleManager, self).get_query_set().filter(deleted__isnull=True)

class DeletedArticleManager(models.Manager):
    def get_query_set(self):
        return super(DeletedArticleManager, self).get_query_set().filter(deleted__isnull=False).order_by('-deleted')

class Article(models.Model):
    topic = models.ForeignKey(Topic)
    text = models.TextField(u'Текст')
    filter = models.CharField(u'Фильтр', max_length=50, choices=[(k, k) for k in filters.keys()])
    created = models.DateTimeField(default=datetime.now, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    author = models.ForeignKey(Profile)
    guest_name = models.CharField(max_length=255, blank=True)
    deleted = models.DateTimeField(null=True, db_index=True, blank=True)
    spawned_to = models.OneToOneField(Topic, null=True, blank=True,
                                      related_name='spawned_from_article')
    spam_status = models.CharField(max_length=20, default='clean')
    ip = models.IPAddressField(default='127.0.0.1')
    votes_up = models.PositiveIntegerField(default=0, editable=False)
    votes_down = models.PositiveIntegerField(default=0, editable=False)
    voters = models.ManyToManyField(Profile, through='Vote', related_name='voted_articles')

    objects = ArticleManager()
    deleted_objects = DeletedArticleManager()

    class Meta:
        ordering = ['created']

    def __unicode__(self):
        return u'(%s, %s, %s)' % (self.topic, self.author, self.created.replace(microsecond=0))

    def delete(self):
        topic = self.topic
        super(Article, self).delete()
        if topic.article_set.count() == 0:
            topic.delete()

    def update_vote_counts(self):
        self.votes_up = self.vote_set.filter(value='up').count()
        self.votes_down = self.vote_set.filter(value='down').count()

    def html(self):
        '''
        Возвращает HTML-текст статьи, полученный фильтрацией содержимого
        через указанный фильтр.

cicero/templates/cicero/article_deleted_list.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}Удаленные статьи{% endblock %}

{% block content %}

<h2>Удаленные статьи {% if user_only %}(автор: {{ user_only }}){% endif %}</h2>

{% if object_list|length %}

{% paginator %}

<table>
<thead>
  <tr>
    <th>Топик
    <th>Статья
    <th>Время
    <th>Восстановление
<tbody>
{% for article in object_list %}
  <tr>
    <td>{{ article.topic }}
    <td>{{ article.html|truncatewords_html:"10" }}
    <td>{{ article.deleted|date:"d.m.Y H:i" }}
    <td>
      <form action="{% url cicero.views.article_undelete article.id %}" method="post">
      <button>Восстановить</button>
      </form>
{% endfor %}
</table>

{% paginator %}

{% else %}

<p id="empty">Нет удаленных статей

{% endif %}

{% endblock %}

{% block aside %}
<ul id="nav" class="block">
  <li><a href="{% url cicero_index %}">Начало</a>
  {% if user_only %}
  <li><a href="{{ profile.get_absolute_url }}">Страница пользователя</a>
  {% endif %}
</ul>
{% endblock %}

cicero/templates/cicero/article_edit.html
{% extends "cicero/auth.html" %}

{% block cicero_title %}Редатирование статьи{% endblock %}

{% block content %}

<h2>Редактирование статьи</h2>

<form action="./" method="post" id="edit">
  <p>
    {{ form.filter.label_tag }}
    {{ form.filter }}
    {% if form.filter.errors %}<em class="error">{{ form.filter.errors|join:", " }}</em>{% endif %}

  <p>
    {{ form.text.label_tag }}
    {{ form.text }}
    {% if form.text.errors %}<em class="error">{{ form.text.errors|join:", " }}</em>{% endif %}
  
  <div class="buttons"><button type="submit">Сохранить</button></div>
</form>

{% endblock %}

{% block aside %}
<ul id="breadcrumbs" class="block">
  <li><a href="{% url cicero.views.topic article.topic.forum.slug,article.topic.id %}">Топик</a>
</ul>

{% endblock %}

cicero/templates/cicero/article_list.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}{{ topic }}{% endblock %}

{% block cicero_extrahead %}<link rel="alternate" type="application/atom+xml" href="{% url cicero_feeds url="articles" %}{{ topic.forum.slug }}/{{ topic.id }}/">{% endblock %}

{% block content %}

<div id="subject">
  <h2>{{ topic.subject }}</h2>
  {% ifcanchangetopic profile topic %}
  <div class="meta">
    <a href="{% url cicero.views.topic_edit topic.id %}">Редактировать</a>
  </div>
  {% endifcanchangetopic %}
  {% if topic.spawned_from %}
    {% with topic.spawned_from.topic as source %}
    <div>Отщеплен от топика <a href="{% url cicero.views.topic source.forum.slug,source.id %}">{{ source.subject }}</a></div>
    {% endwith %}
  {% endif %}
</div>

{% paginator %}

<ol>
{% for article in object_list %}
  <li id="{{ article.id }}">
    {% if not article.spawned %}
    <div class="usertext">
      {{ article.html }}
    </div>
    <div class="meta">
      <p class="mutant">{% if article.author.mutant %}<a href="{{ article.author.get_absolute_url }}"><img src="{{ article.author.mutant.url }}" alt=""></a>{% endif %}
      <address>
      {% if not article.from_guest %}
        <a href="{{ article.author.get_absolute_url }}" title="{{ article.author.openid }}">{{ article.author }}</a>
      {% else %}
        {{ article.guest_name }}
      {% endif %}
      </address>
      <p class="time">{{ article.created|date:"d.m.Y H:i" }}
    </div>
    <div class="control">
      {% ifcanchangearticle profile article %}
      <a href="{% url cicero.views.article_edit article.id %}">Редактировать</a>
      <form action="{% url cicero.views.article_delete article.id %}" method="post"><button>Удалить</button></form>
      {% endifcanchangearticle %}
      {% if profile.moderator %}
      <form action="{% url cicero.views.article_spam article.id %}" method="post"><button>Спам</button></form>
      {% if not article.from_guest %}
      {% with article.author.user.scipio_profile.spamer|yesno:"yes,no,unknown" as spamer %}
      {% ifequal spamer "unknown" %}
      <form action="{% url scipio_whitelist %}" method="post"><input type="hidden" name="id" value="{{ article.author_id }}"><button>Whitelist</button></form>
      {% endifequal %}
      {% endwith %}
      {% endif %}      <a href="{% url cicero.views.topic_spawn article.id %}">Отщепить топик</a>
      {% endif %}
    </div>
    {% else %}
    <div class="spawned">
    Отщеплен новый топик "<a href="{% url cicero.views.topic article.spawned_to.forum.slug,article.spawned_to.id %}">{{ article.spawned_to.subject }}</a>".
    </div>
    {% endif %}
{% endfor %}
</ol>

{% paginator %}

{% if topic.old %}
<p>Внимание! Это довольно старый топик, посты в него не попадут в новые, и их
никто не увидит. Пишите пост, если хотите просто дополнить топик, а чтобы задать
новый вопрос -- <a href="{% url cicero.views.forum topic.forum.slug %}">начните новый</a>.
{% endif %}
{% post_form form topic.forum topic %}

{% endblock %}

{% block aside %}
<ul id="breadcrumbs" class="block">
  <li id="index_link"><a href="{% url cicero_index %}">Начало</a>
  <li id="forum_link"><a href="{% url cicero.views.forum topic.forum.slug %}">{{ topic.forum }}</a>
</ul>
{% endblock %}

cicero/templates/cicero/auth.html
{% extends "cicero/base.html" %}
{% load cicero %}

{% block cicero_content %}

<div id="content">
{% block content %}{% endblock %}
</div>

<div id="aside">
{% block aside %}{% endblock %}

{% if profile.moderator %}
<ul id="moderators" class="block">
  <li><a href="{% url all_deleted_articles %}">Все удаленные статьи</a>
  <li><a href="{% url cicero.views.spam_queue %}">Спам</a>
</ul>
{% endif %}

<ul id="misc" class="block">
  <li><a href="{% url scipio_whitelist %}">OpenID whitelist</a>
</ul>

</div>

{% if user.is_authenticated %}
<form action="{% url scipio_logout %}" method="post" id="auth">
  <p>
    <a href="{{ profile.get_absolute_url }}">{{ profile }}</a>
  <div class="buttons"><button type="submit">Выход</button></div>
</form>
{% else %}
<form action="{% url scipio_login %}" method="post" id="auth">
  <p><label>OpenID: <input type="text" name="openid_identifier"></label>
  <div class="buttons"><button type="submit">Вход</button></div>
</form>
{% endif %}

{% endblock %}

cicero/templates/cicero/post_form.html
<form action="{{ action }}" method="post" id="add">
  {% if not topic %}
  <p>
    <label for="id_subject">{{ form.subject.label }}</label>
    {{ form.subject }}
    {% if form.subject.errors %}<em class="error">{{ form.subject.errors|join:", " }}</em>{% endif %}
  {% endif %}
  <p>
    <label for="id_text">{{ form.text.label }}</label>
    {{ form.text }}
    {% if form.text.errors %}<em class="error">{{ form.text.errors|join:", " }}</em>{% endif %}
  {% if not user.is_authenticated %}
  <p>
    <label for="id_name">{{ form.name.label }}</label>
    {{ form.name }}
    {% if form.name.errors %}<em class="error">{{ form.name.errors|join:", " }}</em>{% endif %}
  {% endif %}
  {% if user.is_authenticated %}
  <p>
    <label for="id_filter">{{ form.filter.label }}</label>
    {{ form.filter }}
    {% if form.filter.errors %}<em class="error">{{ form.filter.errors|join:", " }}</em>{% endif %}
  {% endif %}
  <p style="position: absolute; left: -1000px;">
    <label>Это поле — ловушка для роботов, оставьте его пустым</label>
    <input type="text" name="email" value="" tabindex="-1">
    
  
  <div class="buttons"><button type="submit">Добавить</button></div>
</form>

cicero/templates/cicero/spam.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}Спам{% endblock %}

{% block content %}

<h2>Спам</h2>

<p>Ваш пост был распознан форумом как спам. Если вы считаете, что это произошло
ошибочно, свяжитесь с администратором ({{ admins|join:", " }}), чтобы исправить эту ситуацию.

<p>Сохраните текст вашего поста, потому что форум его хранить не будет:

<pre class="usertext">{{ text }}</pre>

{% endblock %}

{% block aside %}
<ul id="nav" class="block">
  <li><a href="{% url cicero_index %}">Начало</a>
</ul>
{% endblock %}

cicero/templates/cicero/spam_queue.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}Подозрение на спам{% endblock %}

{% block content %}

<h2>Подозрение на спам</h2>

{% if object_list|length %}

{% paginator %}

<table>
<thead>
  <tr>
    <th>Форум
    <th>Топик
    <th>Автор
    <th>Тип подозрения
    <th>Статья
    <th>Амнистия
<tbody>
{% for article in object_list %}
  <tr>
    <td>{{ article.topic.forum }}
    <td>{{ article.topic }}
    <td>{% if article.from_guest %}{{ article.guest_name }}{% else %}<a href="{{ article.author.openid }}">{{ article.author }}</a>{% endif %}
    <td>{{ article.spam_status }}
    <td>{{ article.html|truncatewords_html:"10" }}
    <td>
      <form action="{% url cicero.views.article_publish article.id %}" method="post">
      <button>Не спам</button>
      </form>
{% endfor %}
</table>

{% paginator %}

<form action="{% url cicero.views.delete_spam %}" method="post">
  <button>Удалить все</button>
</form>

{% else %}

<p id="empty">Очередь пуста

{% endif %}

{% endblock %}

{% block aside %}
<ul id="nav" class="block">
  <li><a href="{% url cicero_index %}">Начало</a>
</ul>
{% endblock %}

cicero/templates/cicero/spam_suspect.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}Модерация{% endblock %}

{% block content %}

<h2>Модерация</h2>

<p>Ваш пост ожидает проверки модератором.</p>

{% if article.from_guest %}
<p>Чтобы ваши посты в будущем могли публиковаться без проверки, их можно подписывать 
вашим OpenID-логином.</p>
{% endif %}

<p><li id="forum_link"><a href="{% url cicero.views.forum article.topic.forum.slug %}">{{ article.topic.forum }}</a>

{% endblock %}

cicero/templates/cicero/spawn_topic.html
{% extends "cicero/auth.html" %}

{% block cicero_title %}Отщепление топика{% endblock %}

{% block content %}

<h2>Отщепление статьи в новый топик</h2>

<form action="./" method="post" id="spawn">
  <div id="reference">
    <p>Автор: {% if article.from_guest %}{{ article.guest_name }}{% else %}{{ article.author }}{% endif %}
    <div>
      <p>Текст:<p>
      <div class="usertext">{{ article.html }}</div>
    </div>
  </div>
  <p>
    <label for="id_subject">{{ form.subject.label }}</label>
    {{ form.subject }}
    {% if form.subject.errors %}<em class="error">{{ form.subject.errors|join:", " }}</em>{% endif %}

  <table>
    <caption>Включить еще статьи</caption>
    {% for id, article in form.fields.articles.choices %}
    <tr>
      <td><input type="checkbox" name="articles" value="{{ id }}">
      <td>{% if article.from_guest %}{{ article.guest_name }}{% else %}{{ article.author }}{% endif %}
      <td>{{ article.html|truncatewords_html:30 }}
    {% endfor %}
  </table>
  {% if form.articles.errors %}<em class="error">{{ form.articles.errors|join:", " }}</em>{% endif %}

  <div class="buttons"><button type="submit">Отщепить</button></div>
</form>

{% endblock %}

{% block aside %}
<ul id="breadcrumbs" class="block">
  <li><a href="{% url cicero.views.topic article.topic.forum.slug,article.topic.id %}">Топик</a>
</ul>

{% endblock %}

cicero/templates/cicero/topic_edit.html
{% extends "cicero/auth.html" %}

{% block cicero_title %}Редатирование топика{% endblock %}

{% block content %}

<h2>Редактирование топика</h2>

<form action="./" method="post" id="edit">
  <p>
    <label for="id_text">{{ form.subject.label }}</label>
    {{ form.subject }}
    {% if form.subject.errors %}<em class="error">{{ form.subject.errors|join:", " }}</em>{% endif %}
  
  <div class="buttons"><button type="submit">Сохранить</button></div>
</form>

{% endblock %}

{% block aside %}
<ul id="breadcrumbs" class="block">
  <li><a href="{% url cicero.views.topic article.topic.forum.slug,article.topic.id %}">Топик</a>
</ul>

{% endblock %}

cicero/templates/cicero/topic_list.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}Форум {{ forum }}{% endblock %}

{% block cicero_extrahead %}<link rel="alternate" type="application/atom+xml" href="{% url cicero_feeds url="articles" %}{{ forum.slug }}/">{% endblock %}

{% block content %}

<h2>{{ forum }}</h2>

<form id="search_form" action="{% url cicero.views.search forum.slug %}" method="get">
  <p><input type="search" name="term">
  <div class="buttons"><button type="submit">Искать</button></div>
</form>

{% paginator %}

{% setnews object_list %}
{% topic_list_block object_list %}

{% paginator %}

{% post_form form forum %}

{% endblock %}

{% block aside %}
<ul id="breadcrumbs" class="block">
  <li id="index_link"><a href="{% url cicero_index %}">Начало</a>
</ul>

{% if user.is_authenticated %}
<div id="mark_read" class="block">
  <form action="mark_read/" method="post">
    <button type="submit">Прочитать форум</button>
  </form>
  <form action="../mark_read/" method="post">
    <button type="submit">Прочитать все</button>
  </form>
</div>
{% endif %}

{% endblock %}

cicero/templates/cicero/topic_list_block.html
<ol>
{% for topic in topics %}
  <li {% if topic.new %}class="new"{% endif %}><a href="{% url cicero.views.topic topic.forum.slug,topic.id %}">{{ topic }}</a>
{% endfor %}
</ol>

cicero/templates/cicero/user_topics.html
{% extends "cicero/auth.html" %}
{% load cicero %}

{% block cicero_title %}Статьи пользователя "{{ author_profile }}"{% endblock %}

{% block content %}

<h2>Статьи пользователя "{{ author_profile }}"</h2>

{% if object_list %}

{% paginator %}
{% topic_list_block object_list %}
{% paginator %}

{% else %}
<p id="empty">У пользователя нет статей.
{% endif %}

{% endblock %}

{% block aside %}
<ul id="breadcrumbs" class="block">
  <li id="index_link"><a href="{% url cicero_index %}">Начало</a>
  <li><a href="{{ author_profile.get_absolute_url }}">Страница пользователя</a>
</ul>

{% endblock %}